# Change these first
owner: ory # Your GitHub username
repo: status # Your GitHub repository name

# Add your sites here
sites:
  - name: Website
    url: https://www.ory.sh
  - name: Kubernetes Helm Charts
    url: http://k8s.ory.sh/helm/
  - name: Ory Console
    url: https://console.ory.sh/
    expectedStatusCodes:
      - 200
      - 302
  - name: Ory Kratos API
    url: https://project.console.ory.sh/api/kratos/public/health/ready
  - name: Ory Demo (Legacy)
    url: "$SECRET_STAGING_SITE"
  - name: Ory Kratos API (Staging)
    url: "$SECRET_STAGING_ORY_KRATOS_API"
  - name: Ory Console (Staging)
    url: "$SECRET_STAGING_ORY_CONSOLE"
    expectedStatusCodes:
      - 200
      - 302
  - name: Slack Invite Bot
    url: https://slack.ory.sh/
  - name: SQA Web API
    url: "$SECRET_SQA_WEB_SITE"
  - name: SQA API
    url: "$SECRET_SQA_SITE"
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: Corsar API
    url: "https://corsar.ory.sh/orgs/ory/repos?__host=api.github.com&__proto=https&per_page=10&page=1"
    
status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.ory.sh
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Ory Status
  introTitle: "Ory Builds Open Source Identity Infrastructure and Services."
  introMessage: This is Ory's real-time status page.
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://www.ory.sh/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
commitMessages:
  commitAuthorName: "ory-bot"
  commitAuthorEmail: "60093411+ory-bot@users.noreply.github.com"

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
  
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
